### ISSUE TITLE
No Unitful support

### ISSUE THREAD

**Issue by freemin7** [HSU-ANT/ACME.jl#17]
Unitful.jl is a nice library which allows type inference over physical units making unit conversion errors less likely.
I tried the following:
```
circ = @circuit begin
                j_in = voltagesource(9u"V")
                j_out = voltageprobe()
                j_in[+] == j_out[+]
                j_in[-] == j_out[-]
              end
```
Currently i am getting a `ERROR: DimensionError:  and V are not dimensionally compatible.`
You might want to look into Unitful and whether supporting it makes sense for you.

**Comment by martinholters** [comment]
Agree this would be super nice to support. Unfortunately it's not just writing the code in a way that just happens to work with unitful numbers. Internally, it's quite likely that quantities of different units are collected in the same vector, but for performance, we definitely want that vector elements to be concretely typed, so that leaves dimensionless as best option _internally_.

The surface, however, would definitely benefit from supporting units. It's just that I'm reluctant to add dependencies. But if we get something like https://github.com/JuliaLang/Pkg.jl/issues/1285 eventually, I'd definitely like to add Unitful as an optional dependency.

**Comment by bhalonen** [comment]
Will also note that supporting Unitful APIs makes life much easier to get started. Have lost weeks of work putting the wrong unit into a complex program I did not understand.
