### ISSUE TITLE
Readme uses deprecated syntax

### ISSUE THREAD

**Issue by freemin7** [HSU-ANT/ACME.jl#18]
The readme contains:
`sin(2π*1000/44100*(0:44099).')`

when i run this in Julia 1.3.1 i get this error:
`ERROR: syntax: the ".'" operator is discontinued
`

**Comment by martinholters** [comment]
Good catch! (For the un-initiated: when I wrote this 4 years ago (to the day!), `sin` was one of a bunch of functions that would broadcast automatically and `.'` was syntax for transposition.) I've updated the same code in `gettingstarted.md` at some point but forgot the README...

Feel like opening a PR to fix this? (Otherwise I'll probably come around to doing so in a couple of days.)

**Comment by freemin7** [comment]
I wouldn't mind you doing it. ;-)
